export class VersionData{ public id: number;public version: number;constructor(obj:any){this.id=obj.id;this.version=obj.version;}}

export class TransformData{ public id: number;public eng: string;public chn: string;public kor: number;public jpn: number;constructor(obj:any){this.id=obj.id;this.eng=obj.eng;this.chn=obj.chn;this.kor=obj.kor;this.jpn=obj.jpn;}}

export class CodeData{ public id: number;public code: string;constructor(obj:any){this.id=obj.id;this.code=obj.code;}}

export class BasicData{ public id: number;public type: string;public value: number;constructor(obj:any){this.id=obj.id;this.type=obj.type;this.value=obj.value;}}

export class TitleData{ public id: number;public bool_init_title: number;public name: string;public attribute1: string;public amount1: number;public attribute2: number;public amount2: number;public attribute3: number;public amount3: number;constructor(obj:any){this.id=obj.id;this.bool_init_title=obj.bool_init_title;this.name=obj.name;this.attribute1=obj.attribute1;this.amount1=obj.amount1;this.attribute2=obj.attribute2;this.amount2=obj.amount2;this.attribute3=obj.attribute3;this.amount3=obj.amount3;}}

export class DomainData{ public id: number;public building_id: number;public building: string;public level: number;public dragon_badge: number;public tiger_badge: number;public phoenix_badge: number;public tortoise_badge: number;public resource: string;public efficiency: number;public rate: number;public describe: string;public efficiency_describe: string;public upgrade_: string;constructor(obj:any){this.id=obj.id;this.building_id=obj.building_id;this.building=obj.building;this.level=obj.level;this.dragon_badge=obj.dragon_badge;this.tiger_badge=obj.tiger_badge;this.phoenix_badge=obj.phoenix_badge;this.tortoise_badge=obj.tortoise_badge;this.resource=obj.resource;this.efficiency=obj.efficiency;this.rate=obj.rate;this.describe=obj.describe;this.efficiency_describe=obj.efficiency_describe;this.upgrade_=obj.upgrade_;}}

export class LevelData{ public id: number;public title: string;public phase: number;public step: number;public name: string;public exp_require: number;public consciousness_require: number;public physique_require: number;public attack: number;public rate_base: number;public item_expand: number;public rate_expand: number;public max_amount: number;public item_expand1: number;public rate_expand1: number;public max_amount2: number;public max_rate: number;constructor(obj:any){this.id=obj.id;this.title=obj.title;this.phase=obj.phase;this.step=obj.step;this.name=obj.name;this.exp_require=obj.exp_require;this.consciousness_require=obj.consciousness_require;this.physique_require=obj.physique_require;this.attack=obj.attack;this.rate_base=obj.rate_base;this.item_expand=obj.item_expand;this.rate_expand=obj.rate_expand;this.max_amount=obj.max_amount;this.item_expand1=obj.item_expand1;this.rate_expand1=obj.rate_expand1;this.max_amount2=obj.max_amount2;this.max_rate=obj.max_rate;}}

export class PhasebreakData{ public id: number;public title: string;public level: number;public phase: number;public break_type: number;public exp_require: number;public consciousness_require: number;public physique_require: number;public skill_require1: number;public skill_level1: number;public skill_require2: number;public skill_level2: number;public skill_require3: number;public skill_level3: number;public skill_require4: number;public skill_level4: number;public skill_require5: number;public skill_level5: number;public skill_require6: number;public skill_level6: number;public skill_require7: number;public skill_level7: number;public skill_require8: number;public skill_level8: number;public item_require1: number;public item_amount1: number;public item_require2: number;public item_amount2: number;public item_require3: number;public item_amount3: number;public item_require4: number;public item_amount4: number;public award_item1: number;public award_amount1: number;public award_item2: number;public award_amount2: number;public award_item3: number;public award_amount3: number;public award_item4: number;public award_amount4: number;public award_item5: number;public award_amount5: number;constructor(obj:any){this.id=obj.id;this.title=obj.title;this.level=obj.level;this.phase=obj.phase;this.break_type=obj.break_type;this.exp_require=obj.exp_require;this.consciousness_require=obj.consciousness_require;this.physique_require=obj.physique_require;this.skill_require1=obj.skill_require1;this.skill_level1=obj.skill_level1;this.skill_require2=obj.skill_require2;this.skill_level2=obj.skill_level2;this.skill_require3=obj.skill_require3;this.skill_level3=obj.skill_level3;this.skill_require4=obj.skill_require4;this.skill_level4=obj.skill_level4;this.skill_require5=obj.skill_require5;this.skill_level5=obj.skill_level5;this.skill_require6=obj.skill_require6;this.skill_level6=obj.skill_level6;this.skill_require7=obj.skill_require7;this.skill_level7=obj.skill_level7;this.skill_require8=obj.skill_require8;this.skill_level8=obj.skill_level8;this.item_require1=obj.item_require1;this.item_amount1=obj.item_amount1;this.item_require2=obj.item_require2;this.item_amount2=obj.item_amount2;this.item_require3=obj.item_require3;this.item_amount3=obj.item_amount3;this.item_require4=obj.item_require4;this.item_amount4=obj.item_amount4;this.award_item1=obj.award_item1;this.award_amount1=obj.award_amount1;this.award_item2=obj.award_item2;this.award_amount2=obj.award_amount2;this.award_item3=obj.award_item3;this.award_amount3=obj.award_amount3;this.award_item4=obj.award_item4;this.award_amount4=obj.award_amount4;this.award_item5=obj.award_item5;this.award_amount5=obj.award_amount5;}}

export class ConsciousnessData{ public id: number;public title: string;public phase: number;public step: number;public name: string;public soul_require: number;public speed: number;constructor(obj:any){this.id=obj.id;this.title=obj.title;this.phase=obj.phase;this.step=obj.step;this.name=obj.name;this.soul_require=obj.soul_require;this.speed=obj.speed;}}

export class PhysiqueData{ public id: number;public title: string;public phase: number;public step: number;public name: string;public gas_require: number;public life: number;constructor(obj:any){this.id=obj.id;this.title=obj.title;this.phase=obj.phase;this.step=obj.step;this.name=obj.name;this.gas_require=obj.gas_require;this.life=obj.life;}}

export class RootData{ public id: number;public title: string;public element_attack: number;public element_resistance: number;public phase: number;public step: number;public name: string;public chaos_require: number;public item_require: number;public amount: number;constructor(obj:any){this.id=obj.id;this.title=obj.title;this.element_attack=obj.element_attack;this.element_resistance=obj.element_resistance;this.phase=obj.phase;this.step=obj.step;this.name=obj.name;this.chaos_require=obj.chaos_require;this.item_require=obj.item_require;this.amount=obj.amount;}}

export class StoreData{ public id: number;public rmb: number;public jade: number;public item_id: number;public first_expand: number;constructor(obj:any){this.id=obj.id;this.rmb=obj.rmb;this.jade=obj.jade;this.item_id=obj.item_id;this.first_expand=obj.first_expand;}}

export class ItemData{ public id: number;public item_id: number;public item_class: number;public item_class_name: string;public name: string;public icon: string;public icon_bg: string;public icon_phase: string;public item_quality: number;public phase: number;public store_phase: number;public rank: string;public min_use_level: number;public max_use_level: string;public valid_sec: string;public boolean_stack: number;public poem: string;public describe: string;public shop_price_money: number;public shop_price_jade: number;public shop_amount_range: number;public sell_price: number;public can_use: number;public is_auto_use: number;public resource_type: string;public resource_id: number;public resource_amount: number;constructor(obj:any){this.id=obj.id;this.item_id=obj.item_id;this.item_class=obj.item_class;this.item_class_name=obj.item_class_name;this.name=obj.name;this.icon=obj.icon;this.icon_bg=obj.icon_bg;this.icon_phase=obj.icon_phase;this.item_quality=obj.item_quality;this.phase=obj.phase;this.store_phase=obj.store_phase;this.rank=obj.rank;this.min_use_level=obj.min_use_level;this.max_use_level=obj.max_use_level;this.valid_sec=obj.valid_sec;this.boolean_stack=obj.boolean_stack;this.poem=obj.poem;this.describe=obj.describe;this.shop_price_money=obj.shop_price_money;this.shop_price_jade=obj.shop_price_jade;this.shop_amount_range=obj.shop_amount_range;this.sell_price=obj.sell_price;this.can_use=obj.can_use;this.is_auto_use=obj.is_auto_use;this.resource_type=obj.resource_type;this.resource_id=obj.resource_id;this.resource_amount=obj.resource_amount;}}

export class EquipmentData{ public id: number;public equipment_id: number;public equipment_class: number;public equipment_class_name: string;public name: string;public icon: string;public icon_bg: string;public icon_phase: string;public equipment_quality: number;public phase: number;public equipment_level: number;public rank: string;public describe: number;public poem: string;public can_use: number;public attack: number;public defence: number;public life: number;public speed: number;public hit: number;public dodge: number;public crit: number;public mf: number;public lines: number;public min_use_level: number;public max_use_level: number;public sell_price: number;public decompose_item: number;public decompose_amount: number;constructor(obj:any){this.id=obj.id;this.equipment_id=obj.equipment_id;this.equipment_class=obj.equipment_class;this.equipment_class_name=obj.equipment_class_name;this.name=obj.name;this.icon=obj.icon;this.icon_bg=obj.icon_bg;this.icon_phase=obj.icon_phase;this.equipment_quality=obj.equipment_quality;this.phase=obj.phase;this.equipment_level=obj.equipment_level;this.rank=obj.rank;this.describe=obj.describe;this.poem=obj.poem;this.can_use=obj.can_use;this.attack=obj.attack;this.defence=obj.defence;this.life=obj.life;this.speed=obj.speed;this.hit=obj.hit;this.dodge=obj.dodge;this.crit=obj.crit;this.mf=obj.mf;this.lines=obj.lines;this.min_use_level=obj.min_use_level;this.max_use_level=obj.max_use_level;this.sell_price=obj.sell_price;this.decompose_item=obj.decompose_item;this.decompose_amount=obj.decompose_amount;}}

export class GroupsData{ public id: number;public type: string;public item_1: number;public item_2: number;public item_3: number;public item_4: number;public item_5: number;public item_6: number;public item_7: number;public item_8: number;public item_9: number;public item_10: number;public item_11: number;public item_12: number;public item_13: number;public item_14: number;public item_15: number;public item_16: number;public item_17: number;public item_18: number;public item_19: number;public item_20: number;public weight_1: number;public weight_2: number;public weight_3: number;public weight_4: number;public weight_5: number;public weight_6: number;public weight_7: number;public weight_8: number;public weight_9: number;public weight_10: number;public weight_11: number;public weight_12: number;public weight_13: number;public weight_14: number;public weight_15: number;public weight_16: number;public weight_17: number;public weight_18: number;public weight_19: number;public weight_20: number;constructor(obj:any){this.id=obj.id;this.type=obj.type;this.item_1=obj.item_1;this.item_2=obj.item_2;this.item_3=obj.item_3;this.item_4=obj.item_4;this.item_5=obj.item_5;this.item_6=obj.item_6;this.item_7=obj.item_7;this.item_8=obj.item_8;this.item_9=obj.item_9;this.item_10=obj.item_10;this.item_11=obj.item_11;this.item_12=obj.item_12;this.item_13=obj.item_13;this.item_14=obj.item_14;this.item_15=obj.item_15;this.item_16=obj.item_16;this.item_17=obj.item_17;this.item_18=obj.item_18;this.item_19=obj.item_19;this.item_20=obj.item_20;this.weight_1=obj.weight_1;this.weight_2=obj.weight_2;this.weight_3=obj.weight_3;this.weight_4=obj.weight_4;this.weight_5=obj.weight_5;this.weight_6=obj.weight_6;this.weight_7=obj.weight_7;this.weight_8=obj.weight_8;this.weight_9=obj.weight_9;this.weight_10=obj.weight_10;this.weight_11=obj.weight_11;this.weight_12=obj.weight_12;this.weight_13=obj.weight_13;this.weight_14=obj.weight_14;this.weight_15=obj.weight_15;this.weight_16=obj.weight_16;this.weight_17=obj.weight_17;this.weight_18=obj.weight_18;this.weight_19=obj.weight_19;this.weight_20=obj.weight_20;}}

export class LinesData{ public id: number;public rank: string;public phase: number;public attribute: string;public min: number;public max: number;constructor(obj:any){this.id=obj.id;this.rank=obj.rank;this.phase=obj.phase;this.attribute=obj.attribute;this.min=obj.min;this.max=obj.max;}}

export class PartnerData{ public id: number;public name: string;public icon: string;public describe: string;public favorite: string;public favorite_class: number;public gift_describe: string;public intimacy: number;public phase_name1: string;public phase_intimacy1: number;public phase_attribute1: string;public phase_amount1: number;public phase_name2: string;public phase_intimacy2: number;public phase_attribute2: string;public phase_amount2: number;public phase_name3: string;public phase_intimacy3: number;public phase_attribute3: string;public phase_amount3: number;public phase_name4: string;public phase_intimacy4: number;public phase_attribute4: string;public phase_amount4: number;public phase_name5: string;public phase_intimacy5: number;public phase_attribute5: string;public phase_amount5: number;constructor(obj:any){this.id=obj.id;this.name=obj.name;this.icon=obj.icon;this.describe=obj.describe;this.favorite=obj.favorite;this.favorite_class=obj.favorite_class;this.gift_describe=obj.gift_describe;this.intimacy=obj.intimacy;this.phase_name1=obj.phase_name1;this.phase_intimacy1=obj.phase_intimacy1;this.phase_attribute1=obj.phase_attribute1;this.phase_amount1=obj.phase_amount1;this.phase_name2=obj.phase_name2;this.phase_intimacy2=obj.phase_intimacy2;this.phase_attribute2=obj.phase_attribute2;this.phase_amount2=obj.phase_amount2;this.phase_name3=obj.phase_name3;this.phase_intimacy3=obj.phase_intimacy3;this.phase_attribute3=obj.phase_attribute3;this.phase_amount3=obj.phase_amount3;this.phase_name4=obj.phase_name4;this.phase_intimacy4=obj.phase_intimacy4;this.phase_attribute4=obj.phase_attribute4;this.phase_amount4=obj.phase_amount4;this.phase_name5=obj.phase_name5;this.phase_intimacy5=obj.phase_intimacy5;this.phase_attribute5=obj.phase_attribute5;this.phase_amount5=obj.phase_amount5;}}

export class EventData{ public id: number;public phase: number;public difficulty: number;public name: string;public describe: string;public choice1: string;public requirement1: string;public require_level1: number;public cost1: number;public cost_id1: number;public cost_amount1: number;public award1: string;public award_id1: number;public award_amount1: number;public choice2: string;public requirement2: number;public require_level2: number;public cost2: string;public cost_id2: number;public cost_amount2: number;public award2: string;public award_id2: number;public award_amount2: number;public choice3: string;public requirement3: number;public require_level3: number;public cost3: number;public cost_id3: number;public cost_amount3: number;public award3: string;public award_id3: number;public award_amount3: number;constructor(obj:any){this.id=obj.id;this.phase=obj.phase;this.difficulty=obj.difficulty;this.name=obj.name;this.describe=obj.describe;this.choice1=obj.choice1;this.requirement1=obj.requirement1;this.require_level1=obj.require_level1;this.cost1=obj.cost1;this.cost_id1=obj.cost_id1;this.cost_amount1=obj.cost_amount1;this.award1=obj.award1;this.award_id1=obj.award_id1;this.award_amount1=obj.award_amount1;this.choice2=obj.choice2;this.requirement2=obj.requirement2;this.require_level2=obj.require_level2;this.cost2=obj.cost2;this.cost_id2=obj.cost_id2;this.cost_amount2=obj.cost_amount2;this.award2=obj.award2;this.award_id2=obj.award_id2;this.award_amount2=obj.award_amount2;this.choice3=obj.choice3;this.requirement3=obj.requirement3;this.require_level3=obj.require_level3;this.cost3=obj.cost3;this.cost_id3=obj.cost_id3;this.cost_amount3=obj.cost_amount3;this.award3=obj.award3;this.award_id3=obj.award_id3;this.award_amount3=obj.award_amount3;}}

export class BoxData{ public id: number;public phase: number;public difficulty: number;public award: string;public award_id: number;public award_amount: number;constructor(obj:any){this.id=obj.id;this.phase=obj.phase;this.difficulty=obj.difficulty;this.award=obj.award;this.award_id=obj.award_id;this.award_amount=obj.award_amount;}}

export class ThreadData{ public id: number;public name: string;public partner: number;public map_id: number;public map: string;public phase: number;public step: number;public difficulty: number;public background: string;public plot: string;public dialogue: string;public threshold: number;public dialogue_branch: number;public choice1: string;public requirement1: number;public require_level1: number;public cost1: number;public cost_id1: number;public cost_amount1: number;public award1: string;public award_id1: number;public award_amount1: number;public choice2: string;public requirement2: number;public require_level2: number;public cost2: number;public cost_id2: number;public cost_amount2: number;public award2: string;public award_id2: number;public award_amount2: number;public choice3: string;public requirement3: number;public require_level3: number;public cost3: number;public cost_id3: number;public cost_amount3: number;public award3: string;public award_id3: number;public award_amount3: number;constructor(obj:any){this.id=obj.id;this.name=obj.name;this.partner=obj.partner;this.map_id=obj.map_id;this.map=obj.map;this.phase=obj.phase;this.step=obj.step;this.difficulty=obj.difficulty;this.background=obj.background;this.plot=obj.plot;this.dialogue=obj.dialogue;this.threshold=obj.threshold;this.dialogue_branch=obj.dialogue_branch;this.choice1=obj.choice1;this.requirement1=obj.requirement1;this.require_level1=obj.require_level1;this.cost1=obj.cost1;this.cost_id1=obj.cost_id1;this.cost_amount1=obj.cost_amount1;this.award1=obj.award1;this.award_id1=obj.award_id1;this.award_amount1=obj.award_amount1;this.choice2=obj.choice2;this.requirement2=obj.requirement2;this.require_level2=obj.require_level2;this.cost2=obj.cost2;this.cost_id2=obj.cost_id2;this.cost_amount2=obj.cost_amount2;this.award2=obj.award2;this.award_id2=obj.award_id2;this.award_amount2=obj.award_amount2;this.choice3=obj.choice3;this.requirement3=obj.requirement3;this.require_level3=obj.require_level3;this.cost3=obj.cost3;this.cost_id3=obj.cost_id3;this.cost_amount3=obj.cost_amount3;this.award3=obj.award3;this.award_id3=obj.award_id3;this.award_amount3=obj.award_amount3;}}

export class MapData{ public id: number;public phase: number;public difficulty: number;public width: number;public depth: number;public drop: number;public drop_min: number;public drop_max: number;public monster_group: number;public warden_group: number;public boss_group: number;public grade: number;constructor(obj:any){this.id=obj.id;this.phase=obj.phase;this.difficulty=obj.difficulty;this.width=obj.width;this.depth=obj.depth;this.drop=obj.drop;this.drop_min=obj.drop_min;this.drop_max=obj.drop_max;this.monster_group=obj.monster_group;this.warden_group=obj.warden_group;this.boss_group=obj.boss_group;this.grade=obj.grade;}}

export class SecretData{ public id: number;public phase: number;public quality: number;public probe_hours: number;public money: number;public dragon_badge: number;public tiger_badge: number;public phoenix_badge: number;public tortoise_badge: number;public drop_group1: number;public amount1: number;public drop_group2: number;public amount2: number;public drop_group3: number;public amount3: number;constructor(obj:any){this.id=obj.id;this.phase=obj.phase;this.quality=obj.quality;this.probe_hours=obj.probe_hours;this.money=obj.money;this.dragon_badge=obj.dragon_badge;this.tiger_badge=obj.tiger_badge;this.phoenix_badge=obj.phoenix_badge;this.tortoise_badge=obj.tortoise_badge;this.drop_group1=obj.drop_group1;this.amount1=obj.amount1;this.drop_group2=obj.drop_group2;this.amount2=obj.amount2;this.drop_group3=obj.drop_group3;this.amount3=obj.amount3;}}

export class MonsterData{ public id: number;public phase: number;public quality: number;public monster_level: number;public name: string;public icon: string;public type: string;public attack: number;public defence: number;public life: number;public speed: number;public gold_attack: number;public wood_attack: number;public water_attack: number;public fire_attack: number;public soil_attack: number;public gold_resistance: number;public wood_resistance: number;public water_resistance: number;public fire_resistance: number;public soil_resistance: number;public dodge: number;public crit: number;public grade: number;public action_tree: number;constructor(obj:any){this.id=obj.id;this.phase=obj.phase;this.quality=obj.quality;this.monster_level=obj.monster_level;this.name=obj.name;this.icon=obj.icon;this.type=obj.type;this.attack=obj.attack;this.defence=obj.defence;this.life=obj.life;this.speed=obj.speed;this.gold_attack=obj.gold_attack;this.wood_attack=obj.wood_attack;this.water_attack=obj.water_attack;this.fire_attack=obj.fire_attack;this.soil_attack=obj.soil_attack;this.gold_resistance=obj.gold_resistance;this.wood_resistance=obj.wood_resistance;this.water_resistance=obj.water_resistance;this.fire_resistance=obj.fire_resistance;this.soil_resistance=obj.soil_resistance;this.dodge=obj.dodge;this.crit=obj.crit;this.grade=obj.grade;this.action_tree=obj.action_tree;}}

export class ActiontreeData{ public id: number;public loop1: number;public loop2: number;public loop3: number;public loop4: number;public loop5: number;public loop6: number;public loop7: number;public loop8: number;constructor(obj:any){this.id=obj.id;this.loop1=obj.loop1;this.loop2=obj.loop2;this.loop3=obj.loop3;this.loop4=obj.loop4;this.loop5=obj.loop5;this.loop6=obj.loop6;this.loop7=obj.loop7;this.loop8=obj.loop8;}}

export class TalentData{ public id: number;public class: number;public phase: number;public full_name: string;public name: string;public type: number;public describe: string;public max_level: number;public class_name: string;public class_point_require: number;public pre_talent_require: number;public cold_round: number;public target: string;public multi_step: number;public element: string;public ratio: number;public damage_per_level: number;public attack_attribute_expand: string;public expand_amount_per_level: number;public buff: number;public debuff: number;public level_2_expand: number;public level_1_expand: number;public attack: number;public defence: number;public life: number;public speed: number;public hit: number;public dodge: number;public crit: number;public mf: number;public gold_attack: number;public wood_attack: number;public water_attack: number;public fire_attack: number;public soil_attack: number;public ignore_resistance: number;constructor(obj:any){this.id=obj.id;this.class=obj.class;this.phase=obj.phase;this.full_name=obj.full_name;this.name=obj.name;this.type=obj.type;this.describe=obj.describe;this.max_level=obj.max_level;this.class_name=obj.class_name;this.class_point_require=obj.class_point_require;this.pre_talent_require=obj.pre_talent_require;this.cold_round=obj.cold_round;this.target=obj.target;this.multi_step=obj.multi_step;this.element=obj.element;this.ratio=obj.ratio;this.damage_per_level=obj.damage_per_level;this.attack_attribute_expand=obj.attack_attribute_expand;this.expand_amount_per_level=obj.expand_amount_per_level;this.buff=obj.buff;this.debuff=obj.debuff;this.level_2_expand=obj.level_2_expand;this.level_1_expand=obj.level_1_expand;this.attack=obj.attack;this.defence=obj.defence;this.life=obj.life;this.speed=obj.speed;this.hit=obj.hit;this.dodge=obj.dodge;this.crit=obj.crit;this.mf=obj.mf;this.gold_attack=obj.gold_attack;this.wood_attack=obj.wood_attack;this.water_attack=obj.water_attack;this.fire_attack=obj.fire_attack;this.soil_attack=obj.soil_attack;this.ignore_resistance=obj.ignore_resistance;}}

export class SkillData{ public id: number;public phase: number;public name: string;public icon: string;public icon_bg: string;public icon_phase: string;public activate_money: number;public activate_jade: number;public max_level: number;public require_level: number;public describe: number;public resource: string;public cost_per_level: number;public ratio: number;public level_2_expand: number;public level_1_expand: number;public attack: number;public defence: number;public life: number;public speed: number;public hit: number;public dodge: number;public crit: number;public mf: number;constructor(obj:any){this.id=obj.id;this.phase=obj.phase;this.name=obj.name;this.icon=obj.icon;this.icon_bg=obj.icon_bg;this.icon_phase=obj.icon_phase;this.activate_money=obj.activate_money;this.activate_jade=obj.activate_jade;this.max_level=obj.max_level;this.require_level=obj.require_level;this.describe=obj.describe;this.resource=obj.resource;this.cost_per_level=obj.cost_per_level;this.ratio=obj.ratio;this.level_2_expand=obj.level_2_expand;this.level_1_expand=obj.level_1_expand;this.attack=obj.attack;this.defence=obj.defence;this.life=obj.life;this.speed=obj.speed;this.hit=obj.hit;this.dodge=obj.dodge;this.crit=obj.crit;this.mf=obj.mf;}}

export class BuffData{ public id: number;public scene: string;public name: string;public describe: string;public class: number;public bool_stack: number;public max_stack: number;public round: number;public type: string;public ratio: number;public expand: number;public icon: string;public describe_: string;constructor(obj:any){this.id=obj.id;this.scene=obj.scene;this.name=obj.name;this.describe=obj.describe;this.class=obj.class;this.bool_stack=obj.bool_stack;this.max_stack=obj.max_stack;this.round=obj.round;this.type=obj.type;this.ratio=obj.ratio;this.expand=obj.expand;this.icon=obj.icon;this.describe_=obj.describe_;}}

export class Q_colorData{ public id: number;public quality: number;public color: string;public code: string;public r: number;public g: number;public b: number;constructor(obj:any){this.id=obj.id;this.quality=obj.quality;this.color=obj.color;this.code=obj.code;this.r=obj.r;this.g=obj.g;this.b=obj.b;}}

export class FormulaData{ public id: number;public name: string;public art_type: string;public require_building: number;public require_level: number;public activate_money: number;public activate_jade: number;public product_id: number;public product_quality: number;public product: string;public item1: number;public amount1: number;public item2: number;public amount2: number;public item3: number;public amount3: number;public item4: number;public amount4: number;constructor(obj:any){this.id=obj.id;this.name=obj.name;this.art_type=obj.art_type;this.require_building=obj.require_building;this.require_level=obj.require_level;this.activate_money=obj.activate_money;this.activate_jade=obj.activate_jade;this.product_id=obj.product_id;this.product_quality=obj.product_quality;this.product=obj.product;this.item1=obj.item1;this.amount1=obj.amount1;this.item2=obj.item2;this.amount2=obj.amount2;this.item3=obj.item3;this.amount3=obj.amount3;this.item4=obj.item4;this.amount4=obj.amount4;}}

export class NameData{ public id: number;public type: string;public name: string;constructor(obj:any){this.id=obj.id;this.type=obj.type;this.name=obj.name;}}

export class SummaryData{ public id: number;public type: number;public type_: string;public before: string;public color: number;public color_terminal: number;public after: number;constructor(obj:any){this.id=obj.id;this.type=obj.type;this.type_=obj.type_;this.before=obj.before;this.color=obj.color;this.color_terminal=obj.color_terminal;this.after=obj.after;}}

export class On_saleData{ public id: number;public loc: number;public name: string;public describe: string;public icon: string;public resource: string;public price: number;public on_sale: number;public purchase_times_limit: number;public valid_start: number;public valid_terminal: number;public item1: number;public amount1: number;public item2: number;public amount2: number;public item3: number;public amount3: number;public item4: number;public amount4: number;public item5: number;public amount5: number;constructor(obj:any){this.id=obj.id;this.loc=obj.loc;this.name=obj.name;this.describe=obj.describe;this.icon=obj.icon;this.resource=obj.resource;this.price=obj.price;this.on_sale=obj.on_sale;this.purchase_times_limit=obj.purchase_times_limit;this.valid_start=obj.valid_start;this.valid_terminal=obj.valid_terminal;this.item1=obj.item1;this.amount1=obj.amount1;this.item2=obj.item2;this.amount2=obj.amount2;this.item3=obj.item3;this.amount3=obj.amount3;this.item4=obj.item4;this.amount4=obj.amount4;this.item5=obj.item5;this.amount5=obj.amount5;}}

export class GuideData{ public id: number;public scene: string;public condition_type: string;public condition_value: number;public require_level: number;public background: string;public plot: string;public dialogue: string;public text: string;public loc_x: number;public loc_y: number;public system_unlock: number;public arrow_callback_id: number;constructor(obj:any){this.id=obj.id;this.scene=obj.scene;this.condition_type=obj.condition_type;this.condition_value=obj.condition_value;this.require_level=obj.require_level;this.background=obj.background;this.plot=obj.plot;this.dialogue=obj.dialogue;this.text=obj.text;this.loc_x=obj.loc_x;this.loc_y=obj.loc_y;this.system_unlock=obj.system_unlock;this.arrow_callback_id=obj.arrow_callback_id;}}

export class StrengthenData{ public id: number;public current_level: number;public rate: number;public when_succeed: number;public when_failed: number;public item_id: number;public item_amount: number;public expectation: number;public ratio_expand: number;public base_expand: number;constructor(obj:any){this.id=obj.id;this.current_level=obj.current_level;this.rate=obj.rate;this.when_succeed=obj.when_succeed;this.when_failed=obj.when_failed;this.item_id=obj.item_id;this.item_amount=obj.item_amount;this.expectation=obj.expectation;this.ratio_expand=obj.ratio_expand;this.base_expand=obj.base_expand;}}

export class AvatarData{ public id: number;public avatar_type: string;public avatar_id: number;public activate_money: number;public activate_jade: number;constructor(obj:any){this.id=obj.id;this.avatar_type=obj.avatar_type;this.avatar_id=obj.avatar_id;this.activate_money=obj.activate_money;this.activate_jade=obj.activate_jade;}}

export class AchievementData{ public id: number;public type: string;public name: string;public class: string;public phase: number;public ids: number;public level: number;public monster: number;public item_id1: number;public amount1: number;public item_id2: number;public amount2: number;public guide: number;constructor(obj:any){this.id=obj.id;this.type=obj.type;this.name=obj.name;this.class=obj.class;this.phase=obj.phase;this.ids=obj.ids;this.level=obj.level;this.monster=obj.monster;this.item_id1=obj.item_id1;this.amount1=obj.amount1;this.item_id2=obj.item_id2;this.amount2=obj.amount2;this.guide=obj.guide;}}

export class RemainsData{ public id: number;public quality: number;public name: string;public loc_x: number;public loc_y: number;public max: number;public monster: number;public max_hour: number;public item_id1: number;public amount1: number;public item_id2: number;public amount2: number;public item_id3: number;public amount3: number;public item_id4: number;public amount4: number;constructor(obj:any){this.id=obj.id;this.quality=obj.quality;this.name=obj.name;this.loc_x=obj.loc_x;this.loc_y=obj.loc_y;this.max=obj.max;this.monster=obj.monster;this.max_hour=obj.max_hour;this.item_id1=obj.item_id1;this.amount1=obj.amount1;this.item_id2=obj.item_id2;this.amount2=obj.amount2;this.item_id3=obj.item_id3;this.amount3=obj.amount3;this.item_id4=obj.item_id4;this.amount4=obj.amount4;}}

export class CouponData{ public id: number;public key: string;public terminal: number;public name: string;public item_id1: number;public amount1: number;public item_id2: number;public amount2: number;public item_id3: number;public amount3: number;public item_id4: number;public amount4: number;constructor(obj:any){this.id=obj.id;this.key=obj.key;this.terminal=obj.terminal;this.name=obj.name;this.item_id1=obj.item_id1;this.amount1=obj.amount1;this.item_id2=obj.item_id2;this.amount2=obj.amount2;this.item_id3=obj.item_id3;this.amount3=obj.amount3;this.item_id4=obj.item_id4;this.amount4=obj.amount4;}}

export class ChallengeData{ public id: number;public phase: number;public name: string;public cost_item: number;public cost_amount: number;public monster: number;public ratio_by_step: number;public drop_group1: number;public amount1: number;public drop_group2: number;public amount2: number;public drop_group3: number;public amount3: number;constructor(obj:any){this.id=obj.id;this.phase=obj.phase;this.name=obj.name;this.cost_item=obj.cost_item;this.cost_amount=obj.cost_amount;this.monster=obj.monster;this.ratio_by_step=obj.ratio_by_step;this.drop_group1=obj.drop_group1;this.amount1=obj.amount1;this.drop_group2=obj.drop_group2;this.amount2=obj.amount2;this.drop_group3=obj.drop_group3;this.amount3=obj.amount3;}}

export class WorldbossData{ public id: number;public range: number;public item_id1: number;public amount1: number;public item_id2: number;public amount2: number;public item_id3: number;public amount3: number;public item_id4: number;public amount4: number;constructor(obj:any){this.id=obj.id;this.range=obj.range;this.item_id1=obj.item_id1;this.amount1=obj.amount1;this.item_id2=obj.item_id2;this.amount2=obj.amount2;this.item_id3=obj.item_id3;this.amount3=obj.amount3;this.item_id4=obj.item_id4;this.amount4=obj.amount4;}}

export class AllianceData{ public id: number;public level: number;public max_member: number;public fund_cost: number;public boss: number;public item_id1: number;public amount1: number;public item_id2: number;public amount2: number;public item_id3: number;public amount3: number;public item_id4: number;public amount4: number;constructor(obj:any){this.id=obj.id;this.level=obj.level;this.max_member=obj.max_member;this.fund_cost=obj.fund_cost;this.boss=obj.boss;this.item_id1=obj.item_id1;this.amount1=obj.amount1;this.item_id2=obj.item_id2;this.amount2=obj.amount2;this.item_id3=obj.item_id3;this.amount3=obj.amount3;this.item_id4=obj.item_id4;this.amount4=obj.amount4;}}

export class TechnologyData{ public id: number;public technology_id: string;public name: string;public level: number;public attribute: string;public efficiency_ratio: number;public fund_cost: number;public alliance_level_requirement: number;constructor(obj:any){this.id=obj.id;this.technology_id=obj.technology_id;this.name=obj.name;this.level=obj.level;this.attribute=obj.attribute;this.efficiency_ratio=obj.efficiency_ratio;this.fund_cost=obj.fund_cost;this.alliance_level_requirement=obj.alliance_level_requirement;}}

export class PositionData{ public id: number;public position_id: number;public name: string;constructor(obj:any){this.id=obj.id;this.position_id=obj.position_id;this.name=obj.name;}}

export class DailyData{ public id: number;public task_type: string;public describe: string;public requirement: number;public item_id1: number;public amount1: number;public item_id2: number;public amount2: number;public item_id3: number;public amount3: number;public item_id4: number;public amount4: number;constructor(obj:any){this.id=obj.id;this.task_type=obj.task_type;this.describe=obj.describe;this.requirement=obj.requirement;this.item_id1=obj.item_id1;this.amount1=obj.amount1;this.item_id2=obj.item_id2;this.amount2=obj.amount2;this.item_id3=obj.item_id3;this.amount3=obj.amount3;this.item_id4=obj.item_id4;this.amount4=obj.amount4;}}
